language: node_js

node_js:
  - "11.10.1"

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: "11.10.1"
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
